[build]
  publish = "public"



# Config for the Netlify Build Plugin: netlify-plugin-fetch-feeds
[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "public/CMS"

    # All the feeds we wish to gather for use in the build
  
    [[plugins.inputs.feeds]]
      name = "KanshiinBlogaa"
      url = "https://blog.goo.ne.jp/2291yamaiku/rss2.xml"
      ttl = 1