[build]
  publish = "public"
  command = "npm run build"

# Config for RSS plugin
[[plugins]]
  package = "/plugins/rss"

  [plugins.inputs]
    # Where should data file reside
    filename = "public/CMS/KanshiinBlog.json"
    
    # Where to output an error log
    errorFile = "public/CMS/rss_log.txt"

    feedUrl = "https://blog.goo.ne.jp/2291yamaiku/rss2.xml"
    retries = 3
    retryDelay = 10 # Seconds