backend:
  name: github
  repo: Asahidake/AsahidakeMApp
  branch: master

# 編集のDraftなどのフローだけど、ローガルで使えなさそうなので、いらないかな？
# publish_mode: editorial_workflow

# For local dev
local_backend: true

media_folder: "public/images/cms"
public_folder: "images/cms"

collections:
  - name: "使い方"
    label: "readMe"
    folder: "content"
    create: true
    slug: "{{fields.slug}}"
    identifier_field: label
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date",format: "YYYY-MM-DD"}
      - {label: "Modified", name: "modified", widget: "string", required: false}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Related", name: "related_post", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "登山道情報"
    name: tozan-joho
    folder: "content/tozanJoho"
    identifier_field: src
    create: true
    delete: true
    format: json
    editor:
      preview: false
    slug: "{{year}}{{month}}{{day}}-{{trail}}"
    summary: "{{trail}} {{year}}年{{month}}月{{day}}日"
    view_filters:
      - label: "旭岳山頂"
        field: trail
        pattern: "旭岳山頂"
      - label: "裾合平・中岳温泉"
        field: trail
        pattern: "裾合平・中岳温泉"
      - label: "天女が原"
        field: trail
        pattern: "天女が原"
      - label: "裏旭"
        field: trail
        pattern: "裏旭"
    fields:
      - label: "登山道"
        name: trail
        widget: select
        options:
          - "旭岳山頂"
          - "裾合平・中岳温泉"
          - "天女が原"
          - "裏旭"
      - label: "日付"
        name: date
        widget: datetime
        dateFormat: "YYYY年MM月DD日"
        timeFormat: false
      - label: "画像データ"
        name: src
        widget: image